[package]
name = "db_schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.163"
sqlx = { version = "0.6.3", features = [ "runtime-tokio-native-tls", "mysql", "macros", "chrono"] }

# Use cargo cmd <COMMAND_NAME> to run
[package.metadata.commands]
lint = "clippy --no-deps"
